### ISSUE TITLE
[Error] aruco_msgs/MarkerArray.h

### ISSUE THREAD

**Issue by Dhivin** [DedaleTSP/ddale_ardrone_nav#1]
/home/dhivin/ey/src/ddale_ardrone_nav-master/src/marker.cpp:6:36: fatal error: aruco_msgs/MarkerArray.h: No such file or directory
compilation terminated.
ddale_ardrone_nav-master/CMakeFiles/readmarker.dir/build.make:62: recipe for target 'ddale_ardrone_nav-master/CMakeFiles/readmarker.dir/src/marker.cpp.o' failed
make[2]: *** [ddale_ardrone_nav-master/CMakeFiles/readmarker.dir/src/marker.cpp.o] Error 1
CMakeFiles/Makefile2:5325: recipe for target 'ddale_ardrone_nav-master/CMakeFiles/readmarker.dir/all' failed
make[1]: *** [ddale_ardrone_nav-master/CMakeFiles/readmarker.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Gingerbreadz** [comment]
It seems you do not have installed the "aruco_ros" package, which is a dependency of this project.
http://wiki.ros.org/aruco_ros
